apiVersion: v2
name: gostwriter
description: Helm chart for deploying Gostwriter
type: application
version: 0.0.4
appVersion: "0.0.1"
keywords:
  - gostwriter
  - transcription
  - git
maintainers:
  - name: jo-hoe
sources:
  - https://github.com/jo-hoe/gostwriter